#!/usr/bin/env python3
"""Put the achievement list into the game, and write the human-readable copy.

    python3 achievements/inline.py

achievements.json is the only place the list is written down. This script
flattens it into the ACHV block in blob-knight-rumpler.html and regenerates
README.md from the same data, so the list in the game, the permanent buffs it
hands out and the list you can read here cannot drift apart.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PAGE = os.path.join(HERE, '..', 'blob-knight-rumpler.html')
SRC = os.path.join(HERE, 'achievements.json')
START = '// --- achievements: generated by achievements/inline.py, do not edit by hand ---\n'
END = '// --- end achievements ---'


# how a reward reads, wherever it is shown
PERK = {
    'move':   lambda n: '+%d%% move speed' % round(n * 100),
    'cd':     lambda n: '\u2212%d%% cooldowns' % round(n * 100),
    'kbOut':  lambda n: '+%d%% knockback' % round(n * 100),
    'kbIn':   lambda n: '\u2212%d%% knockback taken' % round(n * 100),
    'shield': lambda n: '+%d%% shield' % round(n * 100),
    'jump':   lambda n: '+%d%% jump' % round(n * 100),
    'heart':  lambda n: '+%d heart' % n,
}


def perk_label(perk):
    fmt = PERK.get(perk['stat'])
    if not fmt:
        sys.exit('inline.py: unknown perk stat %r' % perk['stat'])
    return fmt(perk['amount'])


def flatten(data):
    out = []
    for a in data['overall']:
        out.append({k: a[k] for k in ('id', 'name', 'line', 'stat', 'need', 'perk')})
    for core in data['cores']:
        for a in core['achievements']:
            row = {k: a[k] for k in ('id', 'name', 'line', 'stat', 'need', 'perk')}
            row['id'] = core['key'] + ':' + row['id']
            row['core'] = core['key']
            out.append(row)
    return out


def js_block(rows):
    lines = []
    for r in rows:
        bits = ["id:'%s'" % r['id'], "name:'%s'" % r['name'].replace("'", "\\'"),
                "line:'%s'" % r['line'].replace("'", "\\'"),
                "stat:'%s'" % r['stat'], 'need:%d' % r['need'],
                "perk:{stat:'%s',amt:%s}" % (r['perk']['stat'], r['perk']['amount'])]
        if 'core' in r:
            bits.append("core:'%s'" % r['core'])
        lines.append('  {' + ', '.join(bits) + '},')
    return START + 'const ACHV = [\n' + '\n'.join(lines) + '\n];\n' + END


def ceiling(data):
    """What a hundred-per-cent save is actually worth, said out loud."""
    total = {}
    items = list(data['overall']) + list(data['cores'][0]['achievements'])
    for a in items:
        total[a['perk']['stat']] = total.get(a['perk']['stat'], 0) + a['perk']['amount']
    return ', '.join(PERK[k](v) for k, v in total.items())


def markdown(data, rows):
    def table(items):
        out = ['| Achievement | How you earn it | Unlocks, for good |', '|---|---|---|']
        for a in items:
            out.append('| **%s** | %s | %s |' % (a['name'], a['line'], perk_label(a['perk'])))
        return '\n'.join(out)

    md = ['# Achievements',
          '',
          'Every achievement in **Blob Knight Rumpler** — %d in all: %d overall and eight '
          'for each of the eight cores. They are tracked as you play, kept in your browser '
          '(the app keeps its own), and shown in the game under **Achievements** on the title '
          'screen, with progress on the ones you have started.'
          % (len(rows), len(data['overall'])),
          '',
          'Each one also unlocks a **permanent buff**. A core\u2019s own eight only apply while '
          'you are carrying that core, so mastering every knight does not stack into one '
          'unstoppable build; the twelve overall apply always. Fully earned, that is at most '
          '%s on one core \u2014 and the **Boosts** toggle on the title screen turns all of it '
          'off, along with the pre-match cards, for a run on the game as it ships.'
          % ceiling(data),
          '',
          'Edit `achievements/achievements.json` and run `python3 achievements/inline.py` to '
          'change the list; this file and the copy inside the game are both generated from it.',
          '',
          '## Overall',
          '',
          table(data['overall']),
          '']
    for core in data['cores']:
        md += ['## %s' % core['name'], '', table(core['achievements']), '']
    return '\n'.join(md)


def main():
    with open(SRC, encoding='utf-8') as f:
        data = json.load(f)
    rows = flatten(data)
    ids = [r['id'] for r in rows]
    if len(set(ids)) != len(ids):
        sys.exit('inline.py: duplicate achievement ids')

    with open(PAGE, encoding='utf-8') as f:
        html = f.read()
    i, j = html.find(START), html.find(END)
    if i < 0 or j < 0:
        sys.exit('inline.py: the ACHV markers are not in the page any more')
    html = html[:i] + js_block(rows) + html[j + len(END):]
    with open(PAGE, 'w', encoding='utf-8') as f:
        f.write(html)

    with open(os.path.join(HERE, 'README.md'), 'w', encoding='utf-8') as f:
        f.write(markdown(data, rows))
    print('inlined %d achievements (%d overall + %d across %d cores) and wrote README.md'
          % (len(rows), len(data['overall']), len(rows) - len(data['overall']), len(data['cores'])))


if __name__ == '__main__':
    main()
