#!/usr/bin/env python3
"""Inline the buff-card art into the game page.

    python3 card-art/inline.py

Reads the twelve .webp files beside this script and rewrites the BUFF_ART block
in blob-knight-rumpler.html with them as data URIs. The page stays one
self-contained file, which is what the Android build and an offline copy both
need - a card is 3-7 KB, the whole deck about 85 KB of base64.

The .webp files are made from the 512px Thrixel originals (see README.md):
    cwebp -q 80 -m 6 <512px png resized to 256> -o <name>.webp
"""
import base64
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PAGE = os.path.join(HERE, '..', 'blob-knight-rumpler.html')
START = '// --- card art: generated by card-art/inline.py, do not edit by hand ---\n'
END = '// --- end card art ---'
# the order the cards are declared in the game
NAMES = ['armor', 'keen', 'quick', 'reach', 'ironheart', 'bulwark',
         'feather', 'boots', 'sledge', 'secondwind', 'deflect', 'adrenaline']


def main():
    lines = []
    total = 0
    for name in NAMES:
        path = os.path.join(HERE, name + '.webp')
        if not os.path.exists(path):
            sys.exit('inline.py: missing ' + path)
        with open(path, 'rb') as f:
            data = f.read()
        total += len(data)
        uri = 'data:image/webp;base64,' + base64.b64encode(data).decode('ascii')
        lines.append("  %s: '%s'," % (name, uri))
    block = START + 'const BUFF_ART = {\n' + '\n'.join(lines) + '\n};\n' + END

    with open(PAGE, encoding='utf-8') as f:
        html = f.read()
    i = html.find(START)
    j = html.find(END)
    if i < 0 or j < 0:
        sys.exit('inline.py: the BUFF_ART markers are not in the page any more')
    html = html[:i] + block + html[j + len(END):]
    with open(PAGE, 'w', encoding='utf-8') as f:
        f.write(html)
    print('inlined %d cards, %.1f KB of art (%.1f KB as base64)'
          % (len(NAMES), total / 1024, total * 4 / 3 / 1024))


if __name__ == '__main__':
    main()
